const actions = {
  GET_ALL: "GET_ALL",
  GET_MOVIES: "GET_MOVIES",
  MOVIES_LOADING: "MOVIES_LOADING",
  SET_MOVIES: "SET_MOVIES",
  GET_CATEGORIES: "GET_CATEGORIES",
  SET_CATEGORIES: "SET_CATEGORIES",
};

export default actions;
